-- Gen IA conversación completa OneMarketer — capa PRD — PRODUCCIÓN
-- Grano: process_date + idcase
--
-- Si la tabla YA tiene data en PRD: NO uses este archivo.
-- Usa en su lugar:
--   sqls/alter_hist_onemarketer_caso_conversacion_ia.sql
--
-- Este DDL es solo para ambientes nuevos (CREATE OR REPLACE borra data).
-- Esquema alineado a docs/prompt_canal_escrito_formato_salida.txt
-- prd-utpbi-data-operation.adf_speech_analytics (US)

CREATE OR REPLACE TABLE `prd-utpbi-data-operation.adf_speech_analytics.hist_onemarketer_caso_conversacion_ia_process_data_prd` (
  process_date DATE,
  idcase INT64,
  waid STRING,
  conversacion_completa STRING,
  message_count INT64,
  audio_transcrito_count INT64,
  ocr_count INT64,
  prompt_name STRING,
  prompt_updated_at TIMESTAMP,
  evaluacion_json STRING,
  precondicion STRING,
  resumen_evaluacion STRING,
  motivacion_del_cliente STRING,
  tipificacion STRING,
  atributo STRING,
  estilo_del_asesor STRING,
  segundo_numero_contacto STRING,
  motivo_no_venta STRING,
  submotivo_no_venta STRING,
  detalle_submotivo_no_venta STRING,
  observaciones_no_venta STRING,
  carreras_de_interes STRING,
  flag_varias_carreras STRING,
  carrera_interes_utp STRING,
  carrera_de_interes_no_encontrada STRING,
  modalidad_deseada STRING,
  sede_deseada STRING,
  informacion_complementaria_clasificacion STRING,
  sondeo_clasificacion STRING,
  argumentario_de_venta_clasificacion STRING,
  cierre_clasificacion STRING,
  informacion_falsa_clasificacion STRING,
  actitud_comercial_clasificacion STRING,
  saludo_score STRING,
  saludo_descripcion STRING,
  despedida_score STRING,
  despedida_descripcion STRING,
  aclara_duda_del_cliente_score STRING,
  aclara_duda_del_cliente_descripcion STRING,
  primera_respuesta_score STRING,
  primera_respuesta_descripcion STRING,
  segunda_respuesta_score STRING,
  segunda_respuesta_descripcion STRING,
  vacios_injustificados_score STRING,
  vacios_injustificados_descripcion STRING,
  corte_intencional_score STRING,
  corte_intencional_descripcion STRING,
  abandono_del_chat_score STRING,
  abandono_del_chat_descripcion STRING,
  tono_despectivo_o_sarcastico_score STRING,
  tono_despectivo_o_sarcastico_descripcion STRING,
  confronta_al_prospecto_score STRING,
  confronta_al_prospecto_descripcion STRING,
  lenguaje_grosero_score STRING,
  lenguaje_grosero_descripcion STRING,
  claridad_y_coherencia_score STRING,
  claridad_y_coherencia_descripcion STRING,
  informacion_complementaria_score STRING,
  informacion_complementaria_descripcion STRING,
  motivacion_score STRING,
  motivacion_descripcion STRING,
  identifica_campus_score STRING,
  identifica_campus_descripcion STRING,
  sondeo_por_interes_score STRING,
  sondeo_por_interes_descripcion STRING,
  argumentario_de_venta_score STRING,
  argumentario_de_venta_descripcion STRING,
  validacion_informacion_argumentario_score STRING,
  validacion_informacion_argumentario_descripcion STRING,
  rebate_score STRING,
  rebate_descripcion STRING,
  rebate_efectivo_score STRING,
  rebate_efectivo_descripcion STRING,
  cierre_score STRING,
  cierre_descripcion STRING,
  resumen_de_venta_score STRING,
  resumen_de_venta_descripcion STRING,
  sentido_de_urgencia_score STRING,
  sentido_de_urgencia_descripcion STRING,
  ortografia_y_signos_de_puntuacion_score STRING,
  ortografia_y_signos_de_puntuacion_descripcion STRING,
  plantillas_whatsapp_score STRING,
  plantillas_whatsapp_descripcion STRING,
  uso_de_flyers_videos_y_artes_score STRING,
  uso_de_flyers_videos_y_artes_descripcion STRING,
  comunicacion_ordenada_y_coherente_score STRING,
  comunicacion_ordenada_y_coherente_descripcion STRING,
  informacion_falsa_score STRING,
  informacion_falsa_descripcion STRING,
  actitud_comercial_score STRING,
  actitud_comercial_descripcion STRING,
  afecta_imagen_negocio_score STRING,
  afecta_imagen_negocio_descripcion STRING,
  analisis_llm STRING,
  load_date DATETIME
)
PARTITION BY process_date
OPTIONS (
  description = 'Gen IA canal escrito — evaluación pauta completa por idcase (consumo)'
);
