-- =============================================================================
-- ALTER TABLES OneMarketer Gen IA — PRODUCCIÓN (idempotente, no borra data)
--
-- Location: US (adf_speech_analytics)
--
-- hist_whatsapp_gen_ia_*  → ya tienen el schema; STT reusa las mismas columnas
--                           (transcripcion, status, json_text, full_response…).
--                           No hace falta ALTER.
--
-- hist_caso_conversacion_ia_* → agrega columnas faltantes de la pauta canal escrito.
--                               Si la tabla no existe, crea solo el esqueleto
--                               (process_date + idcase) y luego ALTER.
--
-- bq query --use_legacy_sql=false --location=US --project_id=prd-utpbi-data-operation \
--   < onemarketer/bigquery/sqls/alter_hist_onemarketer_caso_conversacion_ia.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- RAW
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `prd-utpbi-data-operation.adf_speech_analytics.hist_onemarketer_caso_conversacion_ia_process_data_raw` (
  process_date DATE,
  idcase INT64
)
PARTITION BY process_date
OPTIONS (
  description = 'Gen IA canal escrito — evaluación pauta completa por idcase (raw)'
);

ALTER TABLE `prd-utpbi-data-operation.adf_speech_analytics.hist_onemarketer_caso_conversacion_ia_process_data_raw`
  ADD COLUMN IF NOT EXISTS waid STRING,
  ADD COLUMN IF NOT EXISTS conversacion_completa STRING,
  ADD COLUMN IF NOT EXISTS message_count INT64,
  ADD COLUMN IF NOT EXISTS audio_transcrito_count INT64,
  ADD COLUMN IF NOT EXISTS ocr_count INT64,
  ADD COLUMN IF NOT EXISTS prompt_name STRING,
  ADD COLUMN IF NOT EXISTS prompt_updated_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS json_text STRING,
  ADD COLUMN IF NOT EXISTS evaluacion_json STRING,
  ADD COLUMN IF NOT EXISTS full_response STRING,
  ADD COLUMN IF NOT EXISTS status STRING,
  ADD COLUMN IF NOT EXISTS analisis_llm STRING,
  ADD COLUMN IF NOT EXISTS precondicion STRING,
  ADD COLUMN IF NOT EXISTS resumen_evaluacion STRING,
  ADD COLUMN IF NOT EXISTS motivacion_del_cliente STRING,
  ADD COLUMN IF NOT EXISTS tipificacion STRING,
  ADD COLUMN IF NOT EXISTS tipificacion_detalle STRING,
  ADD COLUMN IF NOT EXISTS atributo STRING,
  ADD COLUMN IF NOT EXISTS estilo_del_asesor STRING,
  ADD COLUMN IF NOT EXISTS segundo_numero_contacto STRING,
  ADD COLUMN IF NOT EXISTS motivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS submotivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS detalle_submotivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS observaciones_no_venta STRING,
  ADD COLUMN IF NOT EXISTS carreras_de_interes STRING,
  ADD COLUMN IF NOT EXISTS flag_varias_carreras STRING,
  ADD COLUMN IF NOT EXISTS carrera_interes_utp STRING,
  ADD COLUMN IF NOT EXISTS carrera_de_interes_no_encontrada STRING,
  ADD COLUMN IF NOT EXISTS modalidad_deseada STRING,
  ADD COLUMN IF NOT EXISTS sede_deseada STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS sondeo_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS cierre_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS saludo_score STRING,
  ADD COLUMN IF NOT EXISTS saludo_descripcion STRING,
  ADD COLUMN IF NOT EXISTS despedida_score STRING,
  ADD COLUMN IF NOT EXISTS despedida_descripcion STRING,
  ADD COLUMN IF NOT EXISTS aclara_duda_del_cliente_score STRING,
  ADD COLUMN IF NOT EXISTS aclara_duda_del_cliente_descripcion STRING,
  ADD COLUMN IF NOT EXISTS primera_respuesta_score STRING,
  ADD COLUMN IF NOT EXISTS primera_respuesta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS segunda_respuesta_score STRING,
  ADD COLUMN IF NOT EXISTS segunda_respuesta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS vacios_injustificados_score STRING,
  ADD COLUMN IF NOT EXISTS vacios_injustificados_descripcion STRING,
  ADD COLUMN IF NOT EXISTS corte_intencional_score STRING,
  ADD COLUMN IF NOT EXISTS corte_intencional_descripcion STRING,
  ADD COLUMN IF NOT EXISTS abandono_del_chat_score STRING,
  ADD COLUMN IF NOT EXISTS abandono_del_chat_descripcion STRING,
  ADD COLUMN IF NOT EXISTS tono_despectivo_o_sarcastico_score STRING,
  ADD COLUMN IF NOT EXISTS tono_despectivo_o_sarcastico_descripcion STRING,
  ADD COLUMN IF NOT EXISTS confronta_al_prospecto_score STRING,
  ADD COLUMN IF NOT EXISTS confronta_al_prospecto_descripcion STRING,
  ADD COLUMN IF NOT EXISTS lenguaje_grosero_score STRING,
  ADD COLUMN IF NOT EXISTS lenguaje_grosero_descripcion STRING,
  ADD COLUMN IF NOT EXISTS claridad_y_coherencia_score STRING,
  ADD COLUMN IF NOT EXISTS claridad_y_coherencia_descripcion STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_score STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_descripcion STRING,
  ADD COLUMN IF NOT EXISTS motivacion_score STRING,
  ADD COLUMN IF NOT EXISTS motivacion_descripcion STRING,
  ADD COLUMN IF NOT EXISTS identifica_campus_score STRING,
  ADD COLUMN IF NOT EXISTS identifica_campus_descripcion STRING,
  ADD COLUMN IF NOT EXISTS sondeo_por_interes_score STRING,
  ADD COLUMN IF NOT EXISTS sondeo_por_interes_descripcion STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_score STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS validacion_informacion_argumentario_score STRING,
  ADD COLUMN IF NOT EXISTS validacion_informacion_argumentario_descripcion STRING,
  ADD COLUMN IF NOT EXISTS rebate_score STRING,
  ADD COLUMN IF NOT EXISTS rebate_descripcion STRING,
  ADD COLUMN IF NOT EXISTS rebate_efectivo_score STRING,
  ADD COLUMN IF NOT EXISTS rebate_efectivo_descripcion STRING,
  ADD COLUMN IF NOT EXISTS cierre_score STRING,
  ADD COLUMN IF NOT EXISTS cierre_descripcion STRING,
  ADD COLUMN IF NOT EXISTS resumen_de_venta_score STRING,
  ADD COLUMN IF NOT EXISTS resumen_de_venta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS sentido_de_urgencia_score STRING,
  ADD COLUMN IF NOT EXISTS sentido_de_urgencia_descripcion STRING,
  ADD COLUMN IF NOT EXISTS ortografia_y_signos_de_puntuacion_score STRING,
  ADD COLUMN IF NOT EXISTS ortografia_y_signos_de_puntuacion_descripcion STRING,
  ADD COLUMN IF NOT EXISTS plantillas_whatsapp_score STRING,
  ADD COLUMN IF NOT EXISTS plantillas_whatsapp_descripcion STRING,
  ADD COLUMN IF NOT EXISTS uso_de_flyers_videos_y_artes_score STRING,
  ADD COLUMN IF NOT EXISTS uso_de_flyers_videos_y_artes_descripcion STRING,
  ADD COLUMN IF NOT EXISTS comunicacion_ordenada_y_coherente_score STRING,
  ADD COLUMN IF NOT EXISTS comunicacion_ordenada_y_coherente_descripcion STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_score STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_descripcion STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_score STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_descripcion STRING,
  ADD COLUMN IF NOT EXISTS afecta_imagen_negocio_score STRING,
  ADD COLUMN IF NOT EXISTS afecta_imagen_negocio_descripcion STRING,
  ADD COLUMN IF NOT EXISTS load_date DATETIME;

-- ---------------------------------------------------------------------------
-- PRD
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `prd-utpbi-data-operation.adf_speech_analytics.hist_onemarketer_caso_conversacion_ia_process_data_prd` (
  process_date DATE,
  idcase INT64
)
PARTITION BY process_date
OPTIONS (
  description = 'Gen IA canal escrito — evaluación pauta completa por idcase (consumo)'
);

ALTER TABLE `prd-utpbi-data-operation.adf_speech_analytics.hist_onemarketer_caso_conversacion_ia_process_data_prd`
  ADD COLUMN IF NOT EXISTS waid STRING,
  ADD COLUMN IF NOT EXISTS conversacion_completa STRING,
  ADD COLUMN IF NOT EXISTS message_count INT64,
  ADD COLUMN IF NOT EXISTS audio_transcrito_count INT64,
  ADD COLUMN IF NOT EXISTS ocr_count INT64,
  ADD COLUMN IF NOT EXISTS prompt_name STRING,
  ADD COLUMN IF NOT EXISTS prompt_updated_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS evaluacion_json STRING,
  ADD COLUMN IF NOT EXISTS precondicion STRING,
  ADD COLUMN IF NOT EXISTS resumen_evaluacion STRING,
  ADD COLUMN IF NOT EXISTS motivacion_del_cliente STRING,
  ADD COLUMN IF NOT EXISTS tipificacion STRING,
  ADD COLUMN IF NOT EXISTS tipificacion_detalle STRING,
  ADD COLUMN IF NOT EXISTS atributo STRING,
  ADD COLUMN IF NOT EXISTS estilo_del_asesor STRING,
  ADD COLUMN IF NOT EXISTS segundo_numero_contacto STRING,
  ADD COLUMN IF NOT EXISTS motivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS submotivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS detalle_submotivo_no_venta STRING,
  ADD COLUMN IF NOT EXISTS observaciones_no_venta STRING,
  ADD COLUMN IF NOT EXISTS carreras_de_interes STRING,
  ADD COLUMN IF NOT EXISTS flag_varias_carreras STRING,
  ADD COLUMN IF NOT EXISTS carrera_interes_utp STRING,
  ADD COLUMN IF NOT EXISTS carrera_de_interes_no_encontrada STRING,
  ADD COLUMN IF NOT EXISTS modalidad_deseada STRING,
  ADD COLUMN IF NOT EXISTS sede_deseada STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS sondeo_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS cierre_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_clasificacion STRING,
  ADD COLUMN IF NOT EXISTS saludo_score STRING,
  ADD COLUMN IF NOT EXISTS saludo_descripcion STRING,
  ADD COLUMN IF NOT EXISTS despedida_score STRING,
  ADD COLUMN IF NOT EXISTS despedida_descripcion STRING,
  ADD COLUMN IF NOT EXISTS aclara_duda_del_cliente_score STRING,
  ADD COLUMN IF NOT EXISTS aclara_duda_del_cliente_descripcion STRING,
  ADD COLUMN IF NOT EXISTS primera_respuesta_score STRING,
  ADD COLUMN IF NOT EXISTS primera_respuesta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS segunda_respuesta_score STRING,
  ADD COLUMN IF NOT EXISTS segunda_respuesta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS vacios_injustificados_score STRING,
  ADD COLUMN IF NOT EXISTS vacios_injustificados_descripcion STRING,
  ADD COLUMN IF NOT EXISTS corte_intencional_score STRING,
  ADD COLUMN IF NOT EXISTS corte_intencional_descripcion STRING,
  ADD COLUMN IF NOT EXISTS abandono_del_chat_score STRING,
  ADD COLUMN IF NOT EXISTS abandono_del_chat_descripcion STRING,
  ADD COLUMN IF NOT EXISTS tono_despectivo_o_sarcastico_score STRING,
  ADD COLUMN IF NOT EXISTS tono_despectivo_o_sarcastico_descripcion STRING,
  ADD COLUMN IF NOT EXISTS confronta_al_prospecto_score STRING,
  ADD COLUMN IF NOT EXISTS confronta_al_prospecto_descripcion STRING,
  ADD COLUMN IF NOT EXISTS lenguaje_grosero_score STRING,
  ADD COLUMN IF NOT EXISTS lenguaje_grosero_descripcion STRING,
  ADD COLUMN IF NOT EXISTS claridad_y_coherencia_score STRING,
  ADD COLUMN IF NOT EXISTS claridad_y_coherencia_descripcion STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_score STRING,
  ADD COLUMN IF NOT EXISTS informacion_complementaria_descripcion STRING,
  ADD COLUMN IF NOT EXISTS motivacion_score STRING,
  ADD COLUMN IF NOT EXISTS motivacion_descripcion STRING,
  ADD COLUMN IF NOT EXISTS identifica_campus_score STRING,
  ADD COLUMN IF NOT EXISTS identifica_campus_descripcion STRING,
  ADD COLUMN IF NOT EXISTS sondeo_por_interes_score STRING,
  ADD COLUMN IF NOT EXISTS sondeo_por_interes_descripcion STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_score STRING,
  ADD COLUMN IF NOT EXISTS argumentario_de_venta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS validacion_informacion_argumentario_score STRING,
  ADD COLUMN IF NOT EXISTS validacion_informacion_argumentario_descripcion STRING,
  ADD COLUMN IF NOT EXISTS rebate_score STRING,
  ADD COLUMN IF NOT EXISTS rebate_descripcion STRING,
  ADD COLUMN IF NOT EXISTS rebate_efectivo_score STRING,
  ADD COLUMN IF NOT EXISTS rebate_efectivo_descripcion STRING,
  ADD COLUMN IF NOT EXISTS cierre_score STRING,
  ADD COLUMN IF NOT EXISTS cierre_descripcion STRING,
  ADD COLUMN IF NOT EXISTS resumen_de_venta_score STRING,
  ADD COLUMN IF NOT EXISTS resumen_de_venta_descripcion STRING,
  ADD COLUMN IF NOT EXISTS sentido_de_urgencia_score STRING,
  ADD COLUMN IF NOT EXISTS sentido_de_urgencia_descripcion STRING,
  ADD COLUMN IF NOT EXISTS ortografia_y_signos_de_puntuacion_score STRING,
  ADD COLUMN IF NOT EXISTS ortografia_y_signos_de_puntuacion_descripcion STRING,
  ADD COLUMN IF NOT EXISTS plantillas_whatsapp_score STRING,
  ADD COLUMN IF NOT EXISTS plantillas_whatsapp_descripcion STRING,
  ADD COLUMN IF NOT EXISTS uso_de_flyers_videos_y_artes_score STRING,
  ADD COLUMN IF NOT EXISTS uso_de_flyers_videos_y_artes_descripcion STRING,
  ADD COLUMN IF NOT EXISTS comunicacion_ordenada_y_coherente_score STRING,
  ADD COLUMN IF NOT EXISTS comunicacion_ordenada_y_coherente_descripcion STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_score STRING,
  ADD COLUMN IF NOT EXISTS informacion_falsa_descripcion STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_score STRING,
  ADD COLUMN IF NOT EXISTS actitud_comercial_descripcion STRING,
  ADD COLUMN IF NOT EXISTS afecta_imagen_negocio_score STRING,
  ADD COLUMN IF NOT EXISTS afecta_imagen_negocio_descripcion STRING,
  ADD COLUMN IF NOT EXISTS analisis_llm STRING,
  ADD COLUMN IF NOT EXISTS load_date DATETIME;
