-- Despliegue PRD — Gen IA OneMarketer WhatsApp (etapa 1 audios + etapa 2 conversación)
--
-- IMPORTANTE: SP y tablas hist van en adf_speech_analytics (US), NO en raw_onemarketer.
-- Vista hilo completo en raw_onemarketer (us-central1).
--
-- Orden:
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/tables/hist_onemarketer_whatsapp_gen_ia_raw.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/tables/hist_onemarketer_whatsapp_gen_ia_prd.sql
--
-- -- Anexar formato JSON a canal_escrito_prompt (us-central1):
-- bq query --use_legacy_sql=false --location=us-central1 \
--   < onemarketer/bigquery/sqls/update_sys_prompts_canal_escrito.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/tables/hist_onemarketer_caso_conversacion_ia_raw.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/tables/hist_onemarketer_caso_conversacion_ia_prd.sql
--
-- bq query --use_legacy_sql=false --location=us-central1 \
--   < onemarketer/bigquery/views/v_onemarketer_caso_hilo_completo.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/procedures/sp_onemarketer_caso_conversacion_ia.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/procedures/sp_onemarketer_whatsapp_gen_ia.sql
--
-- CALL (un solo job — etapa 1 llama etapa 2 al final):
--   CALL `prd-utpbi-data-operation.adf_speech_analytics.sp_onemarketer_whatsapp_gen_ia`(DATE '2026-06-22');
--
-- Re-solo etapa 2 (sin re-transcribir audios):
--   CALL `prd-utpbi-data-operation.adf_speech_analytics.sp_onemarketer_caso_conversacion_ia`(DATE '2026-06-22', NULL);
