-- Despliegue PRD — Gen IA OneMarketer WhatsApp (etapa 1 audios + etapa 2 conversación)
--
-- IMPORTANTE: SP y tablas hist van en adf_speech_analytics (US), NO en raw_onemarketer.
-- Vista hilo completo en raw_onemarketer (us-central1).
-- Orquestación diaria: Cloud Workflows — ver onemarketer/docs/guia-workflow.txt
--
-- Orden (tablas con data → usar ALTER, no CREATE OR REPLACE):
--
-- -- Schema caso conversación (idempotente, no borra data):
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/sqls/alter_hist_onemarketer_caso_conversacion_ia.sql
--
-- -- Prompt canal_escrito (us-central1):
-- bq query --use_legacy_sql=false --location=us-central1 \
--   < onemarketer/bigquery/sqls/update_sys_prompts_canal_escrito.sql
--
-- bq query --use_legacy_sql=false --location=us-central1 \
--   < onemarketer/bigquery/views/v_onemarketer_caso_hilo_completo.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/procedures/sp_onemarketer_caso_conversacion_ia_23.sql
--
-- bq query --use_legacy_sql=false --location=US \
--   < onemarketer/bigquery/procedures/sp_onemarketer_whatsapp_gen_ia_24.sql
--
-- Workflow (recomendado):
--   gcloud workflows deploy onemarketer-daily-pipeline ...
--   (ETL CF → SP STT lotes → SP Gemini)
--
-- Manual etapa 1 (STT; ya NO llama etapa 2):
--   CALL `…sp_onemarketer_whatsapp_gen_ia`(DATE '2026-06-22');
--
-- Manual etapa 2 (sin re-transcribir):
--   CALL `…sp_onemarketer_caso_conversacion_ia`(DATE '2026-06-22', NULL);
--
-- Nota: hist_onemarketer_whatsapp_gen_ia_* no requieren ALTER (STT reusa las columnas).
